version: '3.8'

services:
  java-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/usuarios
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - app-network

  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile_db  # Usando o Dockerfile_db para construir o serviço de banco de dados
    container_name: postgres-db
    environment:
      - POSTGRES_DB=usuarios
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
